// @ts-nocheck
'use client';
import {useEffect,useRef,useState} from 'react';
import {Battle,TANKS,MAPS,EQUIPMENT,stats,purchaseEquipment} from '../lib/battle.mjs';
import {MIN_PITCH,MAX_PITCH,killTier} from '../lib/ballistics.mjs';
import {BattleMusic,MUSIC_THEMES} from '../lib/music.mjs';
import {Crosshair,Shield,ChevronRight,Settings2,Volume2,VolumeX,Maximize,ArrowLeft,Flame,MoveUpRight,Coins,Target,Flag,Pause,Play,RotateCcw} from 'lucide-react';
const DEFAULT={credits:0,wins:0,owned:{barrel:[0],tracks:[0],ammo:[0],armor:[0]},gear:{barrel:0,tracks:0,ammo:0,armor:0}};
const CATS={barrel:'炮管',tracks:'履带',ammo:'弹药',armor:'装甲'};
function readSave(){try{let s=JSON.parse(localStorage.getItem('ironfront-save-v1')||'null');if(!s)return structuredClone(DEFAULT);if(!Number.isFinite(s.credits)||s.credits<0||!Number.isFinite(s.wins)||s.wins<0)throw Error();for(let k of Object.keys(CATS)){if(!Array.isArray(s.owned?.[k])||!s.owned[k].includes(s.gear?.[k])||!EQUIPMENT[k][s.gear[k]])throw Error();}return s;}catch{return structuredClone(DEFAULT)}}
export default function Game(){
 const starting=useRef(false),host=useRef(null),engine=useRef(null),sim=useRef(null),keys=useRef(new Set()),control=useRef({aim:0,pitch:0,zoom:false,fire:false}),audio=useRef(null),music=useRef(null),silent=useRef(false),pausedRef=useRef(false),modeRef=useRef('garage'),saveRef=useRef(DEFAULT),raf=useRef(0),lastUI=useRef(0);
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState('garage'),[tab,setTab]=useState(null),[selected,setSelected]=useState(0),[map,setMap]=useState(0),[category,setCategory]=useState('barrel'),[save,setSave]=useState(DEFAULT),[hud,setHud]=useState(null),[paused,setPaused]=useState(false),[muted,setMuted]=useState(false),[help,setHelp]=useState(false),[notice,setNotice]=useState(''),[result,setResult]=useState(null),[cinematic,setCinematic]=useState(true),[killBanner,setKillBanner]=useState(null),[viewed,setViewed]=useState(0);
 const enableAudio=()=>{try{audio.current??=new(window.AudioContext||window.webkitAudioContext)();audio.current.resume();music.current??=new BattleMusic(audio.current);music.current.setMuted(silent.current);}catch{}};
 const toggleSound=()=>{enableAudio();silent.current=!silent.current;setMuted(silent.current);music.current?.setMuted(silent.current);};
 const changeMode=(m)=>{modeRef.current=m;setMode(m)};
 const persist=(s)=>{saveRef.current=s;setSave(s);try{localStorage.setItem('ironfront-save-v1',JSON.stringify(s));}catch{setNotice('浏览器禁止存档，本次进度将保留到页面关闭。')}};
 const beep=(type)=>{if(silent.current)return;try{let a=audio.current;if(!a)return;let osc=a.createOscillator(),gain=a.createGain();osc.connect(gain);gain.connect(a.destination);osc.type=type==='fire'?'sawtooth':'triangle';osc.frequency.setValueAtTime(type==='fire'?95:type==='kill'?48:160,a.currentTime);osc.frequency.exponentialRampToValueAtTime(22,a.currentTime+.3);gain.gain.setValueAtTime(.09,a.currentTime);gain.gain.exponentialRampToValueAtTime(.001,a.currentTime+.35);osc.start();osc.stop(a.currentTime+.36);}catch{}};
 useEffect(()=>{persist(readSave());let disposed=false;import('../lib/renderer').then(({TankRenderer})=>{if(disposed)return;try{engine.current=new TankRenderer(host.current,setError);Promise.all([engine.current.ready,engine.current.loadMap(0)]).then(()=>{if(!disposed){setReady(true);engine.current.beginFlyover(undefined,()=>setCinematic(false));}}).catch(()=>{});let last=performance.now();const loop=(now)=>{if(disposed)return;let dt=Math.min((now-last)/1000,.05);last=now;let b=sim.current;let c=control.current;if(modeRef.current==='battle'&&b&&!pausedRef.current){let k=keys.current;b.update(dt,{aim:c.aim,pitch:c.pitch,forward:k.has('KeyW'),back:k.has('KeyS'),left:k.has('KeyA'),right:k.has('KeyD'),boost:k.has('ShiftLeft')||k.has('ShiftRight'),fire:c.fire});let events=b.drain();for(let e of events){if(['fire','impact','kill'].includes(e.type))engine.current.burst(e);if(e.type==='fire'&&e.owner===0||e.type==='hit'&&(e.owner===0||e.target===0)||e.type==='kill')beep(e.type);if(e.type==='hit'&&e.owner===0)setNotice(`命中 +${e.damage}`);if(e.type==='kill'){if(e.owner===0){const tier=killTier(e.kills);setKillBanner({...tier,target:b.tanks[e.target].def.name,key:b.time});music.current?.celebrate(tier.count);}else setNotice(`${b.tanks.find(t=>t.id===e.owner)?.def.name||'友军'} 击毁 ${b.tanks[e.target].def.name}`);}if(e.type==='end'){if(b.result==='victory')persist({...saveRef.current,credits:saveRef.current.credits+b.reward,wins:saveRef.current.wins+1});setResult({victory:b.result==='victory',reward:b.reward,kills:b.kills,damage:Math.round(b.damage),time:Math.floor(b.time)});changeMode('result');music.current?.stop();document.exitPointerLock?.();c.fire=false;}}}
 music.current?.setPaused(modeRef.current!=='battle'||pausedRef.current);if(music.current&&b)music.current.intensity=Math.min(1,.35+(1-b.player.hp/b.player.s.hp)*.35+b.kills*.08);engine.current.render(pausedRef.current?0:dt,c.aim,c.pitch,c.zoom);if(b&&now-lastUI.current>70){setHud({hp:b.player.hp,maxHp:b.player.s.hp,energy:b.player.energy,maxEnergy:b.player.s.maxEnergy,reload:b.player.reload,reloadMax:b.player.s.reload,speed:Math.abs(b.player.speed)*3.6,kills:b.kills,alive:b.player.alive,time:b.time,allies:b.tanks.filter(t=>t.team===0&&t.alive).length,enemies:b.tanks.filter(t=>t.team===1&&t.alive).length,tanks:b.tanks.map(t=>({...t,screen:engine.current.project(t.x,t.z)})),zoom:c.zoom,pitch:b.player.pitch,reticle:engine.current.aimProjection()});lastUI.current=now;}raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);}catch(e){setError('无法启动 3D 渲染，请使用开启硬件加速的桌面浏览器。')}}).catch(()=>setError('游戏资源加载失败，请刷新页面重试。'));
 const clear=()=>{keys.current.clear();control.current.fire=false;control.current.zoom=false};const pause=()=>{if(modeRef.current==='battle'){pausedRef.current=true;setPaused(true);music.current?.setPaused(true);clear();document.exitPointerLock?.();}};
 const down=(e)=>{if(modeRef.current==='deployment'&&e.code==='Escape'){engine.current?.finishFlyover();return;}if(modeRef.current!=='battle')return;if(['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'||e.code==='KeyP'){if(e.repeat)return;if(pausedRef.current){pausedRef.current=false;setPaused(false)}else pause();}else keys.current.add(e.code)};
 const up=(e)=>keys.current.delete(e.code);const move=(e)=>{if(modeRef.current!=='battle'||pausedRef.current)return;if(document.pointerLockElement){control.current.aim-=e.movementX*.0026;control.current.pitch=Math.max(MIN_PITCH,Math.min(MAX_PITCH,control.current.pitch-e.movementY*.0014));}else{control.current.aim=-(e.clientX/window.innerWidth-.5)*Math.PI*2;control.current.pitch=Math.max(MIN_PITCH,Math.min(MAX_PITCH,(.5-e.clientY/window.innerHeight)*.65));}};
 const mouseDown=(e)=>{if(modeRef.current!=='battle'||pausedRef.current||e.target.closest('button'))return;if(e.button===0)control.current.fire=true;if(e.button===2)control.current.zoom=true;host.current?.querySelector('canvas')?.requestPointerLock?.()?.catch?.(()=>{});};
 const mouseUp=(e)=>{if(e.button===0)control.current.fire=false;if(e.button===2)control.current.zoom=false};const context=(e)=>{if(modeRef.current==='battle')e.preventDefault()};const visibility=()=>{if(document.hidden)pause();};const lockChange=()=>{if(!document.pointerLockElement){clear();if(modeRef.current==='battle'&&sim.current?.time>1){pausedRef.current=true;setPaused(true);}}};
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('mousemove',move);window.addEventListener('mousedown',mouseDown);window.addEventListener('mouseup',mouseUp);window.addEventListener('contextmenu',context);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',visibility);document.addEventListener('pointerlockchange',lockChange);
 return()=>{disposed=true;cancelAnimationFrame(raf.current);engine.current?.dispose();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('mousemove',move);window.removeEventListener('mousedown',mouseDown);window.removeEventListener('mouseup',mouseUp);window.removeEventListener('contextmenu',context);window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',visibility);document.removeEventListener('pointerlockchange',lockChange);music.current?.dispose();audio.current?.close();};},[]);
 useEffect(()=>{if(!notice)return;let t=setTimeout(()=>setNotice(''),2500);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{engine.current?.setGear(save.gear);setViewed(save.gear[category]);},[save.gear,ready]);
 useEffect(()=>{engine.current?.setFocus(tab==='arsenal'?category:null);setViewed(saveRef.current.gear[category]);},[tab,category]);
 useEffect(()=>{if(!killBanner)return;const timer=setTimeout(()=>setKillBanner(null),killBanner.count===5?5500:3500);return()=>clearTimeout(timer)},[killBanner]);
 const select=(i)=>{setSelected(i);engine.current?.setTank(i)};
 const start=async()=>{if(!ready||starting.current)return;enableAudio();starting.current=true;setReady(false);try{await engine.current.loadMap(map)}catch{starting.current=false;setReady(true);setError('战场未能加载，请刷新重试');return}starting.current=false;setReady(true);let b=new Battle(selected,map,saveRef.current.gear);sim.current=b;control.current={aim:0,pitch:0,zoom:false,fire:false};keys.current.clear();pausedRef.current=false;setPaused(false);setResult(null);setHud(null);setKillBanner(null);setNotice('');engine.current.start(b);changeMode('deployment');setCinematic(true);engine.current.beginFlyover([b.player.x,0,b.player.z],()=>{setCinematic(false);changeMode('battle');music.current?.play(map);setNotice('全歼敌方 5 辆坦克，赢得战斗');});};
 const garage=()=>{document.exitPointerLock?.();keys.current.clear();sim.current=null;pausedRef.current=false;setPaused(false);changeMode('garage');music.current?.stop();setTab(null);setKillBanner(null);engine.current.setFocus(null);engine.current.buildMap(map,true);engine.current.setTank(selected);setHud(null);setNotice('')};
 const equip=(k,i)=>{let tx=purchaseEquipment(saveRef.current,k,i);if(!tx.ok){setNotice('积分不足，赢得战斗可获得至少 500 积分');return}persist(tx.save);setNotice(tx.purchased?'采购成功，装备已安装':'装备已更换')};
 useEffect(()=>{let ctx=document.modelContext;if(!ctx?.registerTool)return;let ac=new AbortController();Promise.resolve(ctx.registerTool({name:'read_tank_loadout',description:'读取当前坦克、地图和装备积分。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({tank:TANKS[selected].name,map:MAPS[map].name,credits:saveRef.current.credits,gear:saveRef.current.gear})},{signal:ac.signal})).catch(()=>{});return()=>ac.abort()},[selected,map]);
 let def=TANKS[selected],s=stats(def,save.gear);const resume=()=>{pausedRef.current=false;setPaused(false);host.current?.querySelector('canvas')?.requestPointerLock?.()?.catch?.(()=>{})};
 return <main className={'game '+(['battle','deployment','result'].includes(mode)?'is-battle ':'')+(!tab?'is-quiet ':'')+(cinematic?'is-cinematic ':'')+(tab==='arsenal'?'is-arsenal':'')}><div ref={host} className="viewport"/><div className="vignette"/>
 {mode==='garage'&&<><header className="topbar" inert={cinematic}><a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="brand-icon">II</span><span>IRON FRONT<small>废 土 战 线</small></span></a><nav><button className={tab==='garage'?'active':''} disabled={!ready} onClick={()=>{enableAudio();setTab(tab==='garage'?null:'garage')}}>作战车库</button><button className={tab==='arsenal'?'active':''} disabled={!ready} onClick={()=>{enableAudio();setTab(tab==='arsenal'?null:'arsenal')}}>装备军械库 <span>04</span></button></nav><div className="account"><span className="status-dot"/>离线战役<span className="credits"><Coins size={17}/>{save.credits.toLocaleString()}<small>积分</small></span><button aria-label="操作指南" className="icon-button" onClick={()=>setHelp(true)}>?</button></div></header>
 {tab==='garage'&&<section className="vehicle-info"><div className="eyebrow">装甲作战单位 / 0{selected+1}</div><div className="nation">{def.flag} {def.nation} <span>主战系列</span></div><h1>{def.name}</h1><p className="vehicle-type">{def.label} <i/> {def.tag}</p><div className="rating"><Shield size={15}/>{'◆'.repeat(def.armor)}<span>装甲等级 {def.armor+save.gear.armor}</span></div><div className="specs">{[['火力',s.damage,330],['装甲',s.hp,2250],['机动',Math.round(s.speed*3.6),95]].map(([name,v,max])=><div className="spec" key={name}><div><span>{name}</span><strong>{v}<small>{name==='机动'?' km/h':name==='装甲'?' HP':' DMG'}</small></strong></div><div className="meter"><i style={{width:Math.min(100,v/max*100)+'%'}}/></div></div>)}</div><div className="loadout-summary"><span>当前装填</span><strong>{s.reload.toFixed(1)} <small>秒</small></strong></div><div className="small-rule"/><p className="flavor">{'整备你的战车，重返前线。'}<br/>胜利获得 500 积分，击毁额外 +100</p></section>}
 {tab==='garage'&&<div className="hangar-label"><span className="cross">+</span><span>FORWARD OPERATING BASE<small>第七前线补给站 · 装甲整备区</small></span><span className="cross">+</span></div>}
 {tab&& (tab==='garage'?<aside className="mission-panel"><div className="panel-title"><span>部署作战</span><button aria-label="收起作战车库" onClick={()=>setTab(null)}>×</button></div><div className="match-type"><strong>5 <span>VS</span> 5</strong><span>歼灭战<small>你 + 4 名 AI 队友</small></span></div><p className="mission-description">在开放战场自由机动，歼灭敌方全部坦克。</p><div className="section-label">选择战场 <span>04 SECTORS</span></div><div className="maps">{MAPS.map((m,i)=><button key={m.id} disabled={!ready} onClick={()=>{setMap(i);engine.current?.buildMap(i,true);engine.current?.setTank(selected)}} className={'map-card '+m.id+(map===i?' selected':'')}><div className="map-art" style={{backgroundImage:`url(/battlefields/${m.id}-preview.png)`,backgroundSize:'cover',backgroundPosition:'center'}}/><div><strong>{m.name}</strong><small>{m.desc}</small></div><span className="radio"/></button>)}</div><button className="deploy" disabled={!ready} onClick={start}><Crosshair size={21}/>{ready?'出击，进入战场':'正在整备坦克…'}<ChevronRight size={19}/></button><div className="mission-foot">单人战役 · 无需匹配 · {save.wins} 场胜利</div></aside>:<aside className="mission-panel arsenal"><div className="panel-title"><span>装备军械库</span><button aria-label="收起装备军械库" onClick={()=>setTab(null)}>×</button></div><div className="equipment-tabs">{Object.entries(CATS).map(([k,label])=><button className={category===k?'active':''} onClick={()=>setCategory(k)} key={k}>{label}</button>)}</div><p className="mission-description">选择装备预览外观，采购后永久解锁。</p>{EQUIPMENT[category].map((item,i)=><div className={'equipment '+(save.gear[category]===i?'equipped':'')+(viewed===i?' previewing':'')} key={i}><div><span className="equipment-number">0{i+1}</span><strong>{item.name}</strong></div><p>{item.desc}</p><button className="preview-equipment" aria-pressed={viewed===i} onClick={()=>{setViewed(i);engine.current?.previewEquipment(category,i)}}>{viewed===i?'正在预览':'预览外观'}</button><button disabled={save.gear[category]===i} onClick={()=>equip(category,i)}>{save.gear[category]===i?'已装备':save.owned[category].includes(i)?'安装装备':<><Coins size={14}/> {item.price} 积分 · 采购</>}</button></div>)}<button className="text-button" onClick={()=>setTab('garage')}>返回部署 <ChevronRight size={15}/></button></aside>)}
 {tab==='garage'&&<section className="tank-selection"><div className="selection-heading"><span>选择你的战车 <small>SELECT YOUR ARMOR</small></span><span>06 / 六国装甲部队</span></div><div className="tank-cards">{TANKS.map((t,i)=><button className={'tank-card '+(selected===i?'selected':'')} onClick={()=>select(i)} key={t.id}><div className="tank-card-top"><span>{t.flag} {t.nation}</span><small>{String(i+1).padStart(2,'0')}</small></div><strong>{t.name}</strong><div className="tank-card-bottom"><span>{t.tag}</span>{selected===i?<span className="selected-text">已选择 ◆</span>:<ChevronRight size={14}/>}</div></button>)}</div></section>}
 {!tab&&!cinematic&&<div className="quiet-dock"><div><span>{def.flag} {def.name}</span><small>{MAPS[map].name} · 5 VS 5</small></div><button disabled={!ready} onClick={start}>{ready?'立即出击':'正在整备…'} <ChevronRight size={18}/></button></div>}
 {tab==='arsenal'&&<div className="focus-caption"><span>{CATS[category]} / 装备检视</span><strong>{EQUIPMENT[category][viewed].name}</strong><small>{save.gear[category]===viewed?'当前装备':'外观预览 · 采购后生效'}</small></div>}
 <footer inert={cinematic}><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> 移动 <i/> 鼠标 瞄准 <i/> 左键 开火 <i/> 右键 开镜 <i/> <kbd>SHIFT</kbd> 冲刺</span><div><button aria-label="切换音乐与音效" onClick={toggleSound}>{muted?<VolumeX size={16}/>:<Volume2 size={16}/>}</button><button aria-label="全屏" onClick={()=>document.documentElement.requestFullscreen?.().catch(()=>setNotice('浏览器不支持全屏'))}><Maximize size={16}/></button><span>作战就绪 <i className="status-dot"/></span></div></footer></>}
 {(mode==='battle'||mode==='result')&&hud&&<div className={'battle-hud '+(hud.zoom?'zoom':'')}><div className="battle-top"><div className="battle-team ally"><span>联合小队</span><strong>{hud.allies}</strong><span>{'◆'.repeat(hud.allies)}{'◇'.repeat(5-hud.allies)}</span></div><div className="battle-clock"><span>歼灭战</span><strong>{Math.floor(hud.time/60).toString().padStart(2,'0')}:{Math.floor(hud.time%60).toString().padStart(2,'0')}</strong></div><div className="battle-team enemy"><span>{'◆'.repeat(hud.enemies)}{'◇'.repeat(5-hud.enemies)}</span><strong>{hud.enemies}</strong><span>敌方部队</span></div></div><button className="pause-button" aria-label="暂停游戏" onClick={()=>{pausedRef.current=true;setPaused(true);music.current?.setPaused(true);keys.current.clear();control.current.fire=false;control.current.zoom=false;document.exitPointerLock?.()}}><Pause size={20}/></button><button className="battle-mute" aria-label="切换音乐与音效" onClick={toggleSound}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><div className="score-theme">{MUSIC_THEMES[map].title}</div><div className="compass">270 · · · 300 · · · 330 · · · <b>{Math.round(((control.current.aim*180/Math.PI)%360+360)%360)}°</b> · · · 030 · · · 060 · · · 090</div>
 {hud.tanks.filter(t=>t.id!==0&&t.alive&&t.screen.visible&&(t.team===0||sim.current?.clearLine(sim.current.player,t))).map(t=><div key={t.id} className={'tank-label '+(t.team?'enemy':'ally')} style={{left:t.screen.x,top:t.screen.y}}><span>{t.team?'▼':'◆'} {t.def.name} <small>{Math.round(Math.hypot(t.x-sim.current.player.x,t.z-sim.current.player.z))}m</small></span><div><i style={{width:(t.hp/t.s.hp*100)+'%'}}/></div></div>)}
 <div className="reticle" style={hud.reticle?{left:hud.reticle.x,top:hud.reticle.y}:undefined}><div/><span>{hud.reload>0?hud.reload.toFixed(1)+'s':'READY'}</span></div>{hud.zoom&&<div className="scope-label">×2.2 <span>光学瞄具</span></div>}
 <div className="vehicle-hud"><div><Shield size={21}/><strong>{def.name}</strong><small>{hud.speed.toFixed(0)} km/h</small></div><div className="health-readout"><b>{Math.ceil(hud.hp)}</b><span>/ {hud.maxHp} HP</span></div><div className="hp-bar"><i style={{width:hud.hp/hud.maxHp*100+'%'}}/></div><div className="energy-line"><span>SHIFT 冲刺</span><div><i style={{width:hud.energy/hud.maxEnergy*100+'%'}}/></div><small>{Math.ceil(hud.energy/hud.maxEnergy*100)}%</small></div></div><div className="pitch-hud">炮管仰角 <b>{(hud.pitch*180/Math.PI).toFixed(1)}°</b><small>鼠标上下 · 重力弹道</small></div><div className="ammo-hud"><span>01</span><div><strong>{EQUIPMENT.ammo[save.gear.ammo].name}</strong><small>{hud.reload>0?'装填中 · '+hud.reload.toFixed(1)+' 秒':'装填完毕 · 左键开火'}</small><div className="meter"><i style={{width:(1-hud.reload/hud.reloadMax)*100+'%'}}/></div></div><b>∞</b></div><div className="minimap"><div className="map-grid">{sim.current?.obstacles.map((o,i)=><i key={'o'+i} className="map-obstacle" style={{left:(o.x+180)/360*100+'%',top:(180-o.z)/360*100+'%',width:o.w/360*100+'%',height:o.d/360*100+'%'}}/>)}{hud.tanks.map(t=><i key={t.id} className={'map-dot '+(t.team?'hostile':'friendly')+(t.id===0?' player':'')+(!t.alive?' dead':'')} style={{left:(t.x+180)/360*100+'%',top:(180-t.z)/360*100+'%',transform:`translate(-50%,-50%) rotate(${t.aim*180/Math.PI}deg)`}}/>)}</div><span>N ↑ <b>{MAPS[map].name}</b> 360m</span></div><div className="battle-hint">WASD 行驶 · 鼠标瞄准 · 左键开火 · 右键开镜 · SHIFT 冲刺 · P / ESC 暂停</div>{!hud.alive&&mode==='battle'&&<div className="spectator"><strong>战车已被击毁</strong><span>正在观战队友，战斗结束后统一结算</span></div>}</div>}
 {cinematic&&<div className="cinematic-overlay"><div className="letterbox top"/><div className="letterbox bottom"/><div className="flight-caption"><span>IRON FRONT / AIR RECON</span><strong>{ready?'护航飞行 · 接近装甲单位':'正在整备飞行器与战车…'}</strong><small>{def.flag} {def.name} / {MAPS[map].name}</small></div><button className="skip-flight" disabled={!ready} onClick={()=>{enableAudio();engine.current?.finishFlyover()}}>跳过过场 <ChevronRight size={16}/></button></div>}
 {killBanner&&<div key={killBanner.key} role="status" className={'kill-banner tier-'+killBanner.count} style={{'--kill-color':killBanner.color}}><div className="kill-rings"/><div className="kill-count">{String(killBanner.count).padStart(2,'0')}</div><span>{killBanner.en}</span><strong>{killBanner.title}</strong><small>{killBanner.target} 已被你击毁</small><div className="kill-pips">{'◆'.repeat(killBanner.count)}</div></div>}
 {notice&&<div role="status" className="toast">{notice}</div>}{error&&<div className="modal-shade"><div className="dialog"><h2>启动失败</h2><p>{error}</p><button className="deploy" onClick={()=>location.reload()}>重新加载</button></div></div>}
 {paused&&mode==='battle'&&<div className="modal-shade"><div className="dialog"><span className="eyebrow">TACTICAL PAUSE</span><h2>战斗已暂停</h2><p>返回车库会放弃当前战斗，不获得积分。</p><button className="deploy" onClick={resume}><Play size={18}/>继续战斗</button><button className="secondary" onClick={garage}><ArrowLeft size={16}/>返回车库</button></div></div>}
 {mode==='result'&&result&&<div className="modal-shade result-shade"><div className="dialog result"><div className="result-emblem">{result.victory?<Flag size={42}/>:<Shield size={42}/>}</div><span className="eyebrow">{result.victory?'MISSION ACCOMPLISHED':'MISSION FAILED'}</span><h2>{result.victory?'战场属于你':'战线失守'}</h2><p>{result.victory?'敌方部队已全部歼灭。补给积分已入账。':'我方部队已全部被击毁。整备战车，再次出击。'}</p><div className="result-stats"><div><strong>{result.kills}</strong><span>击毁敌车</span></div><div><strong>{result.damage}</strong><span>造成伤害</span></div><div><strong>{Math.floor(result.time/60)}:{String(result.time%60).padStart(2,'0')}</strong><span>作战时间</span></div></div><div className="reward"><Coins size={23}/><strong>+{result.reward}</strong> 作战积分</div><button className="deploy" onClick={garage}>返回车库 · 整备装备 <ChevronRight size={20}/></button><button className="secondary" disabled={!ready} onClick={start}><RotateCcw size={17}/>再次出击</button></div></div>}
 {help&&<div className="modal-shade"><div className="dialog"><span className="eyebrow">FIELD MANUAL / 01</span><h2>车长操作手册</h2><div className="help-list">{[['W / S','前进 / 后退'],['A / D','车身左转 / 右转'],['鼠标移动','左右旋转炮塔，上下控制炮管俯仰'],['鼠标左键','发射（按住连续射击）'],['鼠标右键','按住放大瞄准'],['SHIFT','消耗能量加速，松开恢复'],['P / ESC','暂停 / 释放鼠标']].map(([a,b])=><div key={a}><kbd>{a}</kbd><span>{b}</span></div>)}</div><p>点击战场可锁定鼠标，抬高炮口补偿远距离弹道下坠。消灭 5 辆敌车获胜；己方战车被击毁后可观战队友。积分和装备保存在这台设备的浏览器中。</p><button className="deploy" onClick={()=>setHelp(false)}>明白，准备出击</button></div></div>}
 </main>
}
