// @ts-nocheck
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { TANKS, MAPS, makeObstacles } from './battle.mjs';
const UP=new THREE.Vector3(0,1,0);
export class TankRenderer {
 constructor(host,onError){this.host=host;this.onError=onError;this.models=new Map();this.entities=new Map();this.effects=[];this.loaded={};this.mapAssets={};this.mapToken=0;this.cameraReady=false;this.active=true;this.tick=0;this.shotMeshes=[];this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(47,1,.15,1100);this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;host.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','三维坦克战场');this.world=new THREE.Group();this.scene.add(this.world);this.sun=new THREE.DirectionalLight(0xffd5a0,3.4);this.sun.position.set(-60,95,50);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-95,right:95,top:95,bottom:-95,near:1,far:240});this.sun.shadow.bias=-.001;this.sun.shadow.normalBias=.08;this.scene.add(this.sun,this.sun.target);this.hemi=new THREE.HemisphereLight(0xb6ccdc,0x4c3f2b,1.6);this.hemi.layers.set(1);this.camera.layers.enable(1);this.scene.add(this.hemi);this.fill=new THREE.DirectionalLight(0x83bad4,0);this.fill.position.set(20,12,-30);this.fill.layers.set(1);this.scene.add(this.fill);this.resize=()=>{let w=host.clientWidth,h=host.clientHeight;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()};this.observer=new ResizeObserver(this.resize);this.observer.observe(host);this.resize();this.buildMap(0,true);this.setTank(0);this.ready=Promise.all(TANKS.map(async d=>{let g=await new GLTFLoader().loadAsync('/models/'+d.model+'.glb');if(!this.active){this.disposeObject(g.scene);return;}this.loaded[d.model]=g.scene;if(this.mode==='garage'&&TANKS[this.selected].model===d.model)this.setTank(this.selected);})).catch(e=>{this.onError('坦克资源加载失败，请刷新重试。');throw e;});}
 mat(color,metal=.1,rough=.85){return new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough});}
 mesh(geometry,material,parent,x=0,y=0,z=0){let m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 box(parent,w,h,d,x,y,z,mat){return this.mesh(new THREE.BoxGeometry(w,h,d),mat,parent,x,y,z);}
 tank(def,gear={}){let root=new THREE.Group(),body=new THREE.Group(),turret=new THREE.Group();root.add(body,turret);let source=def.model&&this.loaded[def.model];if(source){let cloned=source.clone(true);cloned.updateMatrixWorld(true);cloned.traverse(o=>{if(o.isMesh){let part=o.clone();part.geometry=o.geometry.clone();part.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();part.applyMatrix4(o.parent.matrixWorld);part.castShadow=true;part.receiveShadow=true;(o.name.startsWith('turret')||o.parent.name.startsWith('turret')?turret:body).add(part);}});}else{let armor=this.mat(def.color,.35,.65),dark=this.mat(0x262a25,.55,.7),edge=this.mat(0x3b4036,.5),rust=this.mat(0x70513a,.4);this.box(body,3.35,.65,5.5,0,1.05,0,armor);let front=this.box(body,3.1,.55,1.9,0,1.38,1.5,armor);front.rotation.x=.16;this.box(body,2.95,.2,3.6,0,1.5,-.65,armor);for(let side of [-1,1]){this.box(body,.65,1.1,5.4,side*1.7,.67,0,dark);for(let j=0;j<7;j++){let wheel=this.mesh(new THREE.CylinderGeometry(.43,.43,.16,14),edge,body,side*2.035,.67,-2.15+j*.71);wheel.rotation.z=Math.PI/2;let hub=this.mesh(new THREE.CylinderGeometry(.16,.16,.18,12),armor,body,side*2.12,.67,-2.15+j*.71);hub.rotation.z=Math.PI/2;}for(let j=0;j<22;j++)for(let y of [.13,1.19])this.box(body,.77,.07,.15,side*1.7,y,-2.55+j*.245,rust);for(let j=0;j<5;j++)this.box(body,.15,.54,.94,side*2,1.27,-2+j*1.02,armor);for(let j=0;j<3;j++)this.box(turret,.6,.16,.42,side*.92,2.61,.25+j*.48,edge);}
 let tw=def.id==='france'?2.25:2.7;this.box(turret,tw,.8,2.5,0,2.05,-.05,armor);for(let s of [-1,1]){let cheek=this.box(turret,1.2,.72,1.7,s*.78,2.1,1,armor);cheek.rotation.y=s*-.23;}this.box(turret,2.5,.55,.9,0,2,-1.55,armor);this.mesh(new THREE.CylinderGeometry(.52,.52,.17,20),edge,turret,-.55,2.57,-.35);this.box(turret,.4,.3,.45,.55,2.69,.1,edge);this.box(turret,.3,.16,.04,.55,2.7,.34,this.mat(0x51898d,.7,.15));let gun=this.mesh(new THREE.CylinderGeometry(.12,.17,4.3,14),armor,turret,0,2.2,3.25);gun.rotation.x=Math.PI/2;let sleeve=this.mesh(new THREE.CylinderGeometry(.2,.2,.62,14),edge,turret,0,2.2,2.75);sleeve.rotation.x=Math.PI/2;this.box(turret,.4,.5,.6,0,2.15,1.25,edge);let bore=this.mesh(new THREE.CircleGeometry(.1,14),this.mat(0x080a08),turret,0,2.2,5.405);let ant=this.mesh(new THREE.CylinderGeometry(.014,.022,2,5),dark,turret,-.95,3.25,-.8);for(let j=0;j<7;j++)this.box(body,1.4,.05,.1,0,1.63,-2+j*.18,dark);}
 // Markings and weathered stowage are attached to the actual vehicle.
 if(gear.armor){let plates=this.mat(0x424a37,.5,.7);for(let side of [-1,1])for(let j=0;j<5;j++)this.box(body,.18,.42,.75,side*2.08,1.5,-1.8+j*.88,plates);if(gear.armor===2)for(let side of [-1,1])for(let j=0;j<3;j++)this.box(turret,.65,.18,.42,side*.78,2.65,.45+j*.5,plates);}if(gear.tracks){let cleat=this.mat(0x81735b,.6,.75);for(let side of [-1,1])for(let j=0;j<12;j++)this.box(body,.16,.09,.22,side*2.15,.17,-2.3+j*.41,cleat);}if(gear.barrel){let muzzle={china:[5.10,2.25],france:[4.92,2.25],japan:[4.55,2.2],abrams:[4.25,2.65],challenger:[4.8,2.75],leopard:[4.9,2.7]}[def.model]||[5.4,2.2];let [base,y]=muzzle;let extension=this.mesh(new THREE.CylinderGeometry(.13,.15,gear.barrel===1?1:.4,16),this.mat(0x424838,.65,.45),turret,0,y,base+(gear.barrel===1?.4:0));extension.rotation.x=Math.PI/2;}let stow=this.mat(0x685940);this.box(body,.65,.4,.7,1.1,1.77,-1.8,stow);let band=this.mat(0xc39145);this.box(turret,.035,.25,.65,1.39,2.12,-.25,band);if(!source){this.mergeParts(body);this.mergeParts(turret);}root.traverse(o=>{if(o.isMesh)o.layers.enable(1)});root.userData={turret,body};return root;}
 mergeParts(group){let batches=new Map();for(let m of [...group.children]){if(!m.isMesh)continue;m.updateMatrix();let g=m.geometry.clone().applyMatrix4(m.matrix);let key=m.material.uuid;if(!batches.has(key))batches.set(key,{mat:m.material,geos:[]});batches.get(key).geos.push(g);group.remove(m);m.geometry.dispose();}for(let b of batches.values()){let g=mergeGeometries(b.geos,false);for(let p of b.geos)p.dispose();if(g)this.mesh(g,b.mat,group);}}
 groundTexture(id){let c=document.createElement('canvas');c.width=c.height=256;let ctx=c.getContext('2d');let img=ctx.createImageData(256,256);let base=id==='snow'?[196,207,209]:id==='mud'?[94,87,65]:id==='city'?[99,100,94]:[161,139,101];for(let i=0;i<img.data.length;i+=4){let n=Math.random()*28-14;for(let k=0;k<3;k++)img.data[i+k]=base[k]+n;img.data[i+3]=255;}ctx.putImageData(img,0,0);for(let i=0;i<250;i++){ctx.strokeStyle='rgba(30,25,18,.13)';ctx.beginPath();let x=Math.random()*256,y=Math.random()*256;ctx.moveTo(x,y);ctx.lineTo(x+Math.random()*15,y+Math.random()*6);ctx.stroke();}let t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(60,60);t.colorSpace=THREE.SRGBColorSpace;return t;}
 disposeObject(obj){obj.traverse(o=>{o.geometry?.dispose();if(o.material)for(let m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}});}
 async loadMap(index){
  let id=MAPS[index].id;
  if(!this.mapAssets[id])this.mapAssets[id]=Promise.all([new GLTFLoader().loadAsync('/battlefields/'+id+'.glb'),new THREE.TextureLoader().loadAsync('/battlefields/'+id+'-indirect.png'),new THREE.TextureLoader().loadAsync('/battlefields/'+id+'-albedo.png')]).then(([g,tex,albedo])=>{tex.flipY=false;tex.colorSpace=THREE.NoColorSpace;tex.channel=0;albedo.flipY=false;albedo.colorSpace=THREE.SRGBColorSpace;return {scene:g.scene,light:tex,albedo};}).catch(e=>{delete this.mapAssets[id];throw e});
  return this.mapAssets[id];
 }
 async buildMap(index,garage=false){
  let token=++this.mapToken;this.disposeObject(this.world);this.world.clear();this.entities.clear();this.effects=[];this.shotMeshes=[];this.mapIndex=index;
  let d=MAPS[index];this.scene.background=new THREE.Color(d.sky);this.scene.fog=new THREE.FogExp2(d.fog,garage?.007:.0037);
  // The ground is temporary while the real Blender static scene loads.
  let placeholder=this.mesh(new THREE.PlaneGeometry(900,900),this.mat(d.color),this.world);placeholder.rotation.x=-Math.PI/2;
  this.sun.color.set(d.id==='snow'?0xdcecff:0xffd5a0);this.sun.intensity=d.id==='mud'?2.5:3.4;
  if(garage){let pad=this.mat(0x595b50,.4,.8);this.mesh(new THREE.CylinderGeometry(8.2,8.6,.16,64),pad,this.world,0,.06,0);let ring=new THREE.Mesh(new THREE.RingGeometry(7.8,7.85,80),new THREE.MeshBasicMaterial({color:0xbca26c,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.15;this.world.add(ring);}
  else{let border=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-178,.15,-178),new THREE.Vector3(178,.15,-178),new THREE.Vector3(178,.15,178),new THREE.Vector3(-178,.15,178)]),new THREE.LineBasicMaterial({color:0xe4ac55,transparent:true,opacity:.6}));this.world.add(border);}
  try{let asset=await this.loadMap(index);if(!this.active||token!==this.mapToken)return;let environment=asset.scene.clone(true);environment.traverse(o=>{if(o.isMesh){o.geometry=o.geometry.clone();o.material=o.material.clone();o.material.map=asset.albedo.clone();o.material.map.needsUpdate=true;o.material.color.set(0xffffff);o.material.lightMap=asset.light;o.material.lightMapIntensity=1.25;o.material.roughness=d.id==='mud'?.52:.9;o.material.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <lights_fragment_begin>',THREE.ShaderChunk.lights_fragment_begin.replace('#if ( NUM_HEMI_LIGHTS > 0 )','#if 0'));};o.material.customProgramCacheKey=()=> 'static-indirect-no-live-sky-v1';o.receiveShadow=true;o.castShadow=true;o.userData.staticIndirect=true;}});this.world.remove(placeholder);this.disposeObject(placeholder);this.world.add(environment);}
  catch(e){if(token===this.mapToken)this.onError('战场资源加载失败，请刷新重试。');}
 }

 setGear(gear){this.gear=gear;if(this.mode==='garage')this.setTank(this.selected);}
 setTank(index){this.mode='garage';this.selected=index;if(this.preview){this.world.remove(this.preview);this.disposeObject(this.preview);}this.preview=this.tank(TANKS[index],this.gear||{});this.preview.rotation.y=-.45;this.world.add(this.preview);this.camera.position.set(10,5.3,12.7);this.camera.lookAt(0,1.45,0);}
 start(battle){this.mode='battle';this.battle=battle;this.preview=null;this.buildMap(MAPS.indexOf(battle.map));for(let t of battle.tanks){let model=this.tank(t.def,t.id===0?this.gear||{}:{});this.world.add(model);let marker=new THREE.Mesh(new THREE.RingGeometry(2.7,2.82,24),new THREE.MeshBasicMaterial({color:t.team?0xe6684c:0x91bda0,side:THREE.DoubleSide,transparent:true,opacity:.65}));marker.rotation.x=-Math.PI/2;marker.position.y=.1;model.add(marker);this.entities.set(t.id,model);}this.cameraReady=false;}
 burst(e){let kill=e.type==='kill',count=kill?25:e.type==='fire'?6:9;let mat=new THREE.MeshBasicMaterial({color:kill?0xffa23e:e.type==='fire'?0xffe6a0:0xf3b563,transparent:true});for(let i=0;i<count;i++){let m=this.mesh(new THREE.IcosahedronGeometry(kill?.4:.15,0),mat.clone(),this.world,e.x,2,e.z);this.effects.push({mesh:m,v:new THREE.Vector3((Math.random()-.5)*(kill?12:5),Math.random()*8,(Math.random()-.5)*(kill?12:5)),life:kill?1.4:.5,max:kill?1.4:.5});}mat.dispose();}
 render(dt,aim=0,pitch=.25,zoom=false){this.tick+=dt;if(this.mode==='garage'){if(this.preview)this.preview.rotation.y=-.45+Math.sin(this.tick*.18)*.09;this.camera.position.set(10,5.3,12.7);this.camera.lookAt(-.3,1.25,0);}else{let b=this.battle;for(let t of b.tanks){let m=this.entities.get(t.id);m.position.set(t.x,0,t.z);m.rotation.y=t.yaw;m.userData.turret.rotation.y=t.aim-t.yaw;if(!t.alive&&!m.userData.dead){m.userData.dead=true;m.traverse(o=>{if(o.isMesh&&o.material?.color)o.material.color.multiplyScalar(.23);});}if(t.alive)m.rotation.z=Math.sin(this.tick*15+t.id)*Math.min(Math.abs(t.speed)*.0008,.012);}
 let p=b.player.alive?b.player:b.tanks.find(t=>t.team===0&&t.alive)||b.player;let dist=zoom?5.7:14;let height=zoom?3:5.4+pitch*9;let desired=new THREE.Vector3(p.x-Math.sin(aim)*dist,height,p.z-Math.cos(aim)*dist);for(let o of b.obstacles){let u=segmentBoxLocal(p.x,p.z,desired.x-p.x,desired.z-p.z,o);if(u!==null){desired.x=p.x+(desired.x-p.x)*Math.max(.18,u-.1);desired.z=p.z+(desired.z-p.z)*Math.max(.18,u-.1);}}
 if(!this.cameraReady){this.camera.position.copy(desired);this.cameraReady=true;}else this.camera.position.lerp(desired,1-Math.exp(-dt*12));this.camera.fov+=( (zoom?25:55)-this.camera.fov)*Math.min(1,dt*12);this.camera.updateProjectionMatrix();this.camera.lookAt(p.x+Math.sin(aim)*70,2.2,p.z+Math.cos(aim)*70);this.sun.position.set(p.x-60,95,p.z+50);this.sun.target.position.set(p.x,0,p.z);for(let m of this.shotMeshes){this.world.remove(m);m.geometry.dispose();m.material.dispose();}this.shotMeshes=[];for(let s of b.shots){let m=this.mesh(new THREE.BoxGeometry(.1,.1,2),new THREE.MeshBasicMaterial({color:0xffe8a8}),this.world,s.x,2.15,s.z);m.rotation.y=Math.atan2(s.dx,s.dz);this.shotMeshes.push(m);}}
 for(let e of this.effects){e.life-=dt;e.mesh.position.addScaledVector(e.v,dt);e.v.y-=9*dt;e.mesh.material.opacity=Math.max(0,e.life/e.max);e.mesh.scale.multiplyScalar(1+dt);if(e.life<=0){this.world.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();}}this.effects=this.effects.filter(e=>e.life>0);this.renderer.render(this.scene,this.camera);}
 project(x,z){let v=new THREE.Vector3(x,4.4,z).project(this.camera);return{x:(v.x*.5+.5)*this.host.clientWidth,y:(-.5*v.y+.5)*this.host.clientHeight,visible:v.z<1&&v.z>-1&&Math.abs(v.x)<1&&Math.abs(v.y)<1};}
 dispose(){this.active=false;this.observer.disconnect();this.disposeObject(this.scene);for(let m of Object.values(this.loaded))this.disposeObject(m);for(let promise of Object.values(this.mapAssets))promise.then(a=>{this.disposeObject(a.scene);a.light.dispose();a.albedo.dispose()}).catch(()=>{});this.renderer.dispose();this.renderer.domElement.remove();}
}
function segmentBoxLocal(x,z,dx,dz,o){let lo=0,hi=1;for(let[v,d,c,s]of[[x,dx,o.x,o.w/2+1],[z,dz,o.z,o.d/2+1]]){if(Math.abs(d)<1e-6){if(v<c-s||v>c+s)return null;}else{let a=(c-s-v)/d,b=(c+s-v)/d;if(a>b)[a,b]=[b,a];lo=Math.max(lo,a);hi=Math.min(hi,b);if(lo>hi)return null;}}return lo;}
