import assert from 'node:assert/strict';
import {Battle,TANKS,MAPS,EQUIPMENT,stats,segmentCircle,segmentBox,purchaseEquipment} from '../lib/battle.mjs';
let passed=[];function test(name,fn){fn();passed.push(name);console.log('PASS',name)}
test('Six nations and four maps',()=>{assert.equal(TANKS.length,6);assert.equal(MAPS.length,4)});
test('Equipment changes actual combat stats',()=>{for(let d of TANKS){let s=stats(d,{barrel:1,tracks:2,ammo:1,armor:2});assert.equal(s.hp,d.hp*1.5);assert.equal(s.damage,Math.round(d.damage*1.2*1.25));assert.equal(s.maxEnergy,140);assert(s.speed>d.speed)}});
test('Each match starts 5v5',()=>{for(let m=0;m<4;m++){let b=new Battle(0,m);assert.equal(b.tanks.filter(t=>t.team===0).length,5);assert.equal(b.tanks.length,10);assert.equal(b.player.hp,1200)}});
test('Movement, energy consumption, recovery and independent turret',()=>{let b=new Battle();b.obstacles=[];b.tanks=b.tanks.slice(0,1);b.result=null;let p=b.player;let z=p.z;b.update(.05,{forward:true,boost:true,aim:1});assert(p.z>z);assert(p.energy<100);assert.equal(p.aim,1);assert.equal(p.yaw,0);b.result=null;b.update(.05,{});assert(p.energy>98.5)});
test('Cover collision and high-speed projectile intersection',()=>{assert.equal(segmentCircle(0,0,0,100,0,50,2.5),.475);assert.equal(segmentBox(0,0,0,100,{x:0,z:50,w:10,d:10}),.45);let b=new Battle();b.obstacles=[{x:0,z:0,w:10,d:10}];let p=b.player;p.x=0;p.z=-8;b.move(p,0,5);assert.equal(p.z,-8)});
test('Shots respect cover, reload, and cause damage',()=>{let b=new Battle();b.obstacles=[];for(let t of b.tanks){t.x=140;t.z=t.id*8;t.reload=100;t.s.speed=0}let p=b.player,e=b.tanks[5];p.x=0;p.z=0;p.aim=0;p.reload=0;e.x=0;e.z=20;assert(b.fire(p));assert(!b.fire(p));for(let i=0;i<4;i++)b.update(.05,{});assert(e.hp<e.s.hp);assert(b.damage>0);let c=new Battle();c.obstacles=[{x:0,z:12,w:10,d:3}];for(let t of c.tanks){t.x=140;t.z=t.id*8;t.reload=100;t.s.speed=0}c.player.x=0;c.player.z=0;c.player.reload=0;c.tanks[5].x=0;c.tanks[5].z=20;c.fire(c.player);for(let i=0;i<4;i++)c.update(.05);assert.equal(c.tanks[5].hp,c.tanks[5].s.hp)});
test('Victory, defeat, and dead-player spectator lifecycle',()=>{let b=new Battle();for(let t of b.tanks.filter(t=>t.team))b.hit(t,99999,0);b.update(.01);assert.equal(b.result,'victory');assert.equal(b.reward,1000);let c=new Battle();c.hit(c.player,9999,5);c.update(.01);assert.equal(c.result,null);for(let t of c.tanks.filter(t=>!t.team))c.hit(t,99999,5);c.update(.01);assert.equal(c.result,'defeat');assert.equal(c.reward,0)});
test('AI matches finish on all four maps',()=>{for(let map=0;map<4;map++){let b=new Battle(0,map);b.player.id=10;for(let i=0;i<36000&&!b.result;i++)b.update(.05);assert(b.result,`AI stuck on ${MAPS[map].id}`);console.log('  ',MAPS[map].name,b.result,Math.round(b.time)+'s')}});
test('Victory credits buy upgrades once and survive save roundtrip',()=>{let save={credits:0,wins:0,owned:{barrel:[0],tracks:[0],ammo:[0],armor:[0]},gear:{barrel:0,tracks:0,ammo:0,armor:0}};assert.equal(purchaseEquipment(save,'tracks',1).ok,false);let b=new Battle();for(let t of b.tanks.filter(t=>t.team))b.hit(t,99999,0);b.update(.01);save.credits+=b.reward;let tx=purchaseEquipment(save,'tracks',1);assert(tx.ok);assert.equal(tx.save.credits,550);let again=purchaseEquipment(tx.save,'tracks',1);assert.equal(again.save.credits,550);assert.equal(again.save.owned.tracks.length,2);let loaded=JSON.parse(JSON.stringify(again.save));assert.equal(loaded.gear.tracks,1);assert(stats(TANKS[0],loaded.gear).speed>TANKS[0].speed);});
console.log(JSON.stringify({passed:passed.length,tests:passed},null,2));
